### ISSUE TITLE
cant install WP-GDPR Contact Form DB 7 add-on on wordpress

### ISSUE THREAD

**Issue by wendelien** [WP-GDPR/wp-gdpr-core#19]
Hi Koen Huybrechts
I uploaded and installed your WP-GDPR Contact Form DB 7 add-on according to your instructions (see the screenshots), but the addon doens’t install on wordpress.
Could you give support. The support section on your website doesn’t accept registrations.
Thanks for helping out!

**Comment by Nobiuss** [comment]
Hi Wendelien,

Thanks for your comment and issue report.

When you install "wp-gdpr-cfdb7-addon" you need to have [CFDB7](https://wordpress.org/plugins/contact-form-cfdb7/) to work with your contact form 7.

Kind regards,
KIM
