### ISSUE TITLE
Bootstrap JS conflict

### ISSUE THREAD

**Issue by mickaelmaury** [WP-GDPR/wp-gdpr-core#20]
Hello I am several websites that have just obtained the update WP-GDPR to version 2. It conflicts with the libraries integrated into the various WordPress themes (eg HOTEL WP, Black Diamond, Community Junction, ...). Here is the message obtained:

bootstrap.min.js:7 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

Uncaught TypeError: jQuery(...).size is not a function

Uncaught TypeError: a.indexOf is not a function

jQuery(...).matchHeight is not a function

jQuery(...).organicTabs is not a function

Uncaught TypeError: Cannot read property 'add' of undefined

This results in a blank page on the GDPR Data Access Request form page, or the form that does not appear on the page, or break page.

Would you have a solution to ensure this compatibility with these different themes? My themes and WordPress are both up to date.

**Comment by mickaelmaury** [comment]
Always errors even with the update in version 2.0.2

https://mickael-maury.fr/ - https://mickael-maury.fr/gdpr-rgpd-demande-de-donnees-personnelles/
WP GDPR: version 2.0.2
WP GDPR Gravity Form Addon: 1.2.1
Gravity Forms: 2.3.2
Empty cache
Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)     at bootstrap.min.js? ver = 2.0.8: 7 jquery.min.js: 2

Uncaught ReferenceError: onepress_js_settings is not defined     at HTMLDocument. <anonymous> (theme.js? ver = 2.0.8: 278)

Export of the form Gravity Forms in attachment.

https://agitaform.mickael-maury.fr/lempdes/ - https://agitaform.mickael-maury.fr/lempdes/gdpr-rgpd-demande-de-donnees-personnelles/


WP GDPR: version 2.0.2
Empty cache
 + [Agitaform & # 8211; Lempdes-sur-Allagnon] Your request for data > '-' converted to & # 8211; in the title of the emails

jquery.fancybox.js? ver = 4.9.6: 1985 Uncaught ReferenceError: jQuery is not defined     at jquery.fancybox.js? ver = 4.9.6: 1985 jquery.min.js: 4

Uncaught TypeError: a.indexOf is not a function     at r.fn.init.r.fn.load (jquery.min.js: 4)

https://alexandra-ventura.fr/ - https://alexandra-ventura.fr/gdprrgpd-demande-de-donnees-personnelles/
WP GDPR: version 2.0.2
WP GDPR WooCommerce add-on: 2.0.0
WooCommerce: 3.4.2
Empty cache
Empty cache jquery.min.js: 4 Uncaught TypeError: a.indexOf is not a function     at r.fn.init.r.fn.load (jquery.min.js: 4)

Uncaught TypeError: jQuery (...) size is not a function     at HTMLDocument. <anonymous> (theme.js? ver = 4.9.6: 22)

https://auvergne-chalet.fr/ - https://auvergne-chalet.fr/gdpr-rgpd-demande-de-donnees-personnelles/
WP GDPR: version 2.0.2
Empty cache
+ [Auvergne Chalet & # 8211; Chalet Chassagne] Your request for data > '-' converted to & # 8211; in the title of the emails

**Comment by Nobiuss** [comment]
Hi Mickael, 

We have looked at all your sites and the errors that you  write in your comment are not the ones you have on your sites. 
I made a[ loom video](https://www.useloom.com/share/113910f40f7d45fb8b855a888fb8162a) so you can see this. 

Kind regads,
KIM

**Comment by mickaelmaury** [comment]
The errors occur after receiving the link by e-mail : 

- GDPR/RGPD - Demande de données personnelles - Mickaël Maury (https://mickael-maury.fr/) : https://www.useloom.com/share/337c014f0f504ab597ac89c4b76b62a8

- GDPR/RGPD - Demande de données personnelles - Alexandra Ventura (http://alexandra-ventura.fr/) : https://www.useloom.com/share/d4ea71d6877a4511b1b2b64b92b8580b

- RGPD –DEMANDE DE DONNÉES PERSONNELLES - Agitaform - Lempdes-sur-Allagnon (https://agitaform.mickael-maury.fr/lempdes/) : 
https://www.useloom.com/share/5ebb9e1f984c4d52ac8e87c1295e91ba

- GDPR/RGPD - Demande de données personnelles - Ecclésia Athéna (https://ecclesia-athena.com/) : 
https://www.useloom.com/share/d44e45291aea419d9a19b97041963981

- GDPR/RGPD - Demande de données personnelles - Auvergne Chalet - Chalet Chassagne (https://auvergne-chalet.fr/):
https://www.useloom.com/share/e3018e4608d94d789f3a05cd59e16875


For security reasons I can not unfortunately send you the links generated by your extension. But you can leave test content on these sites and ask for their removal.
