### ISSUE TITLE
Translation 'wp_gdpr' and 'wp-gdpr'

### ISSUE THREAD

**Issue by mickaelmaury** [WP-GDPR/wp-gdpr-core#21]
You have a mixture between the directives for the language keys 'wp_gdpr' and 'wp-gdpr' which are therefore ignored in the translation files. Ex. PRIVACY CENTER

**Comment by Nobiuss** [comment]
Hi Mickael,

Thanks for your issue report!

We have checked them and did the adjustments.
You will see the changes in the next update.

Glad that you reported this!

Cheers, 
KIM

**Comment by Nobiuss** [comment]
Hi Mickael,

The update is live :-D

Kind regards,
KIM
